### ISSUE TITLE
스플래시 이미지 멈춤 현상

### ISSUE THREAD

**Issue by dev-yakuza** [kasumil/RN#6]
스플래시 이미지 멈춤 현상에 대해서 이슈를 남깁니다.

https://github.com/kasumil/RN/blob/7c578c2160169aed8339086843d75a985730efb1/ch8/MovieApp/android/app/src/main/java/com/movieapp/MainActivity.java#L11-L14

안드로이드는 이 부분에서 `SplashScreen.show`를 통해 스플래시 이미지를 화면에 표시합니다. 소스 코드를 보니 이 함수가 두번 호출되고 있습니다. 이 부분을 다음과 같이 고치면 해결이 될거 같습니다.

```diff
protected void onCreate(Bundle savedInstanceState) {SplashScreen.show(this, R.style.SplashScreenTheme);            
    SplashScreen.show(this, true);
-   super.onCreate(savedInstanceState);SplashScreen.show(this, R.style.SplashScreenTheme);
+  super.onCreate(savedInstanceState);
}
```

그리고 알 수 없는 문자(^M)가 들어가 있네요...앱 실행시 문제가 없다면 무시해도 좋을거 같지만, 혹시 모를 일을 대비해서 지우시는 것을 추천해 드립니다.

**Comment by kasumil** [comment]
오류에 대한 답변 감사합니다.

해당 코드 삭제 후 정상적으로 작동합니다.

2020년 12월 16일 (수) 오후 9:23, JeongHean Kim <notifications@github.com>님이 작성:
